### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by lukekasz** [ysc3839/ImmersiveContextMenu#1]
Which license is the code in the repo under?

**Comment by lukekasz** [comment]
@ysc3839 Any thoughts?

**Comment by ysc3839** [comment]
Sorry, I forget this issue. I don't know if I can "license" this code to others. Since it's decompiled from Windows binaries.

**Comment by ysc3839** [comment]
If you really need a license, I would choice [Unlicense](https://unlicense.org).
